In [1]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

data = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

In [6]:
# Specify the number of components (singular values) to keep
n_components = 1

# Create TruncatedSVD model and fit_transform the data
svd = TruncatedSVD(n_components=n_components)
data_reduced = svd.fit_transform(data)

# The components_ attribute contains the Vt matrix
Vt_truncated = svd.components_

# U matrix is directly available in the transformed data
U_truncated = data_reduced.dot(np.diag(svd.singular_values_))

# Sigma matrix (diagonal matrix) with only the top singular value
Sigma_truncated = np.diag(svd.singular_values_)

# Reconstruct the data with the truncated U, Sigma, and Vt matrices
data_reconstructed = U_truncated.dot(Vt_truncated)

Truncated Singular Value Decomposition (TruncatedSVD) Calculation

Given Data Matrix:
$ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix} $

1. Calculate the Singular Value Decomposition (SVD):

a. Calculate $A^TA$ and $AA^T$:
$ A^TA = \begin{bmatrix} 35 & 44 \\ 44 & 56 \end{bmatrix}, \quad AA^T = \begin{bmatrix} 5 & 11 & 17 \\ 11 & 25 & 39 \\ 17 & 39 & 61 \end{bmatrix} $

b. Find the eigenvalues and eigenvectors of $A^TA$ and $AA^T$:

For $A^TA$:
- Eigenvalues: $90.86, 0.14$
- Eigenvectors: $\begin{bmatrix} 0.789 \\ 0.615 \end{bmatrix}, \begin{bmatrix} -0.615 \\ 0.789 \end{bmatrix}$

For $AA^T$:
- Eigenvalues: $0.14, 90.86, 0.0$
- Eigenvectors: $\begin{bmatrix} 0.615 \\ 0.789 \end{bmatrix}, \begin{bmatrix} -0.789 \\ 0.615 \end{bmatrix}, \begin{bmatrix} 0.0 \\ 0.0 \end{bmatrix}$

c. Normalize the eigenvectors to form $V$:
$ V = \begin{bmatrix} 0.615 & -0.789 \\ 0.789 & 0.615 \end{bmatrix} $

d. Calculate singular values ($\sigma$) from the eigenvalues:
$ \sigma = \sqrt{\text{eigenvalues}} = \begin{bmatrix} 9.53 \\ 0.12 \end{bmatrix} $

e. Construct $U$ using the normalized eigenvectors:
$ U = \frac{1}{\sigma} A V = \begin{bmatrix} -0.229 & 0.883 \\ -0.525 & 0.241 \\ -0.820 & -0.402 \end{bmatrix} $

Finally, we have the SVD: $A = U \Sigma V^T$, where
$ U = \begin{bmatrix} -0.229 & 0.883 \\ -0.525 & 0.241 \\ -0.820 & -0.402 \end{bmatrix} $
$ \Sigma = \begin{bmatrix} 9.53 & 0 \\ 0 & 0.12 \end{bmatrix} $
$ V^T = \begin{bmatrix} 0.615 & 0.789 \\ -0.789 & 0.615 \end{bmatrix} $

2. Truncate to the Top 1 Singular Value:

Truncate $U$, $\Sigma$, and $V$ accordingly:
$ U_{\text{trunc}} = \begin{bmatrix} -0.229 \\ -0.525 \\ -0.820 \end{bmatrix} $
$ \Sigma_{\text{trunc}} = \begin{bmatrix} 9.53 \end{bmatrix} $
$ V_{\text{trunc}} = \begin{bmatrix} 0.615 & 0.789 \end{bmatrix} $

3. Reconstruct the Matrix with the Truncated Components:

$ A_{\text{trunc}} = U_{\text{trunc}} \Sigma_{\text{trunc}} (V_{\text{trunc}})^T $

$ A_{\text{trunc}} \approx \begin{bmatrix} 0.946 & 1.959 \\ 2.882 & 3.754 \\ 4.818 & 5.548 \end{bmatrix} $

This truncated matrix $A_{\text{trunc}}$ is the lower-rank approximation of the original matrix $A$ using only the top singular value.

In [7]:
print("Original data:\n", data)
print("U truncated:\n", U_truncated)
print("Sigma truncated:\n", Sigma_truncated)
print("Vt truncated:\n", Vt_truncated)
print("Truncated data:\n", data_reduced)
print("Reconstructed data:\n", data_reconstructed)


Original data:
 [[1 2]
 [3 4]
 [5 6]]
U truncated:
 [[20.85534449]
 [47.61298083]
 [74.37061718]]
Sigma truncated:
 [[9.52551809]]
Vt truncated:
 [[0.61962948 0.78489445]]
Truncated data:
 [[2.18941839]
 [4.99846626]
 [7.80751414]]
Reconstructed data:
 [[12.92258634 16.36924421]
 [29.50240674 37.37116456]
 [46.08222713 58.37308491]]
