In [31]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./EEG_data.csv')
data=pd.read_csv('./demographic_info.csv')

In [3]:
data = data.rename(columns = {'subject ID': 'SubjectID',' gender':'gender',' age':'age',' ethnicity':'ethnicity'})
df = df.merge(data,how = 'inner',on = 'SubjectID')

In [4]:
df['gender']=df['gender'].replace({'M':1,'F':0})
df['ethnicity']=df['ethnicity'].replace({'Han Chinese':0,'Bengali':1,'English':2})
df.drop(columns = ['SubjectID','VideoID','predefinedlabel'],inplace=True)

In [5]:
df.shape

(12811, 15)

In [6]:
target=df['user-definedlabeln']
features=df.drop(columns=['user-definedlabeln'])

In [7]:
features.head()

Attention  Mediation    Raw      Delta     Theta    Alpha1   Alpha2  \
0       56.0       43.0  278.0   301963.0   90612.0   33735.0  23991.0   
1       40.0       35.0  -50.0    73787.0   28083.0    1439.0   2240.0   
2       47.0       48.0  101.0   758353.0  383745.0  201999.0  62107.0   
3       47.0       57.0   -5.0  2012240.0  129350.0   61236.0  17084.0   
4       44.0       53.0   -8.0  1005145.0  354328.0   37102.0  88881.0   

     Beta1     Beta2   Gamma1   Gamma2  age  ethnicity  gender  
0  27946.0   45097.0  33228.0   8293.0   25          0       1  
1   2746.0    3687.0   5293.0   2740.0   25          0       1  
2  36293.0  130536.0  57243.0  25354.0   25          0       1  
3  11488.0   62462.0  49960.0  33932.0   25          0       1  
4  45307.0   99603.0  44790.0  29749.0   25          0       1

In [9]:
from sklearn.decomposition import PCA

In [16]:
n_components = 10

# Initialize PCA
pca = PCA(n_components=n_components)

# Fit and transform your data
reduced_data = pca.fit_transform(features)

In [17]:
reduced_data.shape

(12811, 10)

In [12]:
explained_variance = np.cumsum(pca.explained_variance_ratio_)
explained_variance

array([0.8672319 , 0.96269746, 0.9844812 , 0.99180117, 0.99531393,
       0.99768694, 0.9991347 , 0.9999993 , 1.        , 1.        ])

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
scaler = StandardScaler()
X=scaler.fit_transform(reduced_data)

In [34]:
from sklearn.model_selection import train_test_split
y=target
X_train,x_test,Y_train,y_test=train_test_split(X,y,random_state=108,test_size=0.27)

In [35]:
X_train.shape

(9352, 10)

In [22]:
Y_train.shape

(9352,)

In [36]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [37]:
svm_classifier = SVC(random_state=108)

# Train the classifier on the training data
svm_classifier.fit(X_train, Y_train)

SVC(random_state=108)

In [38]:
predictions = svm_classifier.predict(x_test).astype(int)
predictions

array([0, 1, 1, ..., 0, 1, 0])

In [39]:
accuracy = accuracy_score(y_test, predictions)
accuracy

0.61809771610292

In [15]:
for n in range(3,11):
    pca = PCA(n_components=n)
    reduced_data = pca.fit_transform(features)
    explained_variance = np.cumsum(pca.explained_variance_ratio_)
    print(explained_variance)

[0.8672319  0.96269746 0.9844812 ]
[0.8672319  0.96269746 0.9844812  0.99180117]
[0.8672319  0.96269746 0.9844812  0.99180117 0.99531393]
[0.8672319  0.96269746 0.9844812  0.99180117 0.99531393 0.99768694]
[0.8672319  0.96269746 0.9844812  0.99180117 0.99531393 0.99768694
 0.9991347 ]
[0.8672319  0.96269746 0.9844812  0.99180117 0.99531393 0.99768694
 0.9991347  0.9999993 ]
[0.8672319  0.96269746 0.9844812  0.99180117 0.99531393 0.99768694
 0.9991347  0.9999993  1.        ]
[0.8672319  0.96269746 0.9844812  0.99180117 0.99531393 0.99768694
 0.9991347  0.9999993  1.         1.        ]


In [41]:
scaler = StandardScaler()
svm_classifier = SVC(random_state=108)

In [43]:
for n in range(3,11):
    pca = PCA(n_components=n)
    reduced_data = pca.fit_transform(features)
    X=scaler.fit_transform(reduced_data)
    X_train,x_test,Y_train,y_test=train_test_split(X,y,random_state=108,test_size=0.27)
    svm_classifier.fit(X_train, Y_train)
    predictions = svm_classifier.predict(x_test).astype(int)
    accuracy = accuracy_score(y_test, predictions)
    print(accuracy)

0.5964151488869616
0.5949696444058976
0.5969933506793871
0.5987279560566637
0.5981497542642382
0.5995952587453021
0.6019080659150043
0.61809771610292


In [13]:

df_pca1 = pd.DataFrame(reduced_data,
					columns=['PC{}'.
					format(i+1)
						for i in range(n_components)])

                PC1            PC2            PC3            PC4  \
0     -3.125385e+05   -6792.507690   24678.006907    8498.133717   
1     -5.533435e+05  -33091.224522  -13617.336603   -7246.819374   
2      2.068179e+05  212265.117545   48506.972002   95173.363804   
3      1.365404e+06 -339206.064592   21224.945518  -21199.515724   
4      4.329016e+05  104431.800350   17680.709222  -26788.774740   
...             ...            ...            ...            ...   
12806 -5.026744e+05  -55562.721763   13440.039515   -1372.753454   
12807 -1.174554e+05  750835.421371  235184.854750  -19539.096601   
12808  6.953287e+04  -32986.874459  -14870.708203    2248.597705   
12809 -2.672920e+05  -95094.894026  -11214.749576   -3092.425763   
12810  7.705578e+05  890860.511955   33868.308582 -188732.477743   

                PC5            PC6           PC7           PC8         PC9  \
0       -873.056405   -5402.349212   4943.065901  -9908.607051 -226.367010   
1      -1787.947282    3986